#!/bin/bash

remote=$1
host=`hostname`
call="request_port/$host"

api_response=''
local_ip=''
outside_ip=''

get_ips () {
  local_ip=`ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | tr '\n' ','`
  outside_ip=`curl -s ifconfig.io`
}

api_call () {
  get_ips
  api_response=`curl -s $remote:3000/a/$call?local_ip=$local_ip\&outside_ip=$outside_ip`
}

api_call
echo $api_response

lines=`ps aux | grep $api_response | wc -l`

if [ $lines -eq 1 ]
then
  echo 'Restarting tunnel...'
  screen -dmS tnnl autossh -M 12399 -oPubkeyAuthentication=yes -oPasswordAuthentication=no -oLogLevel=error  -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no -R $api_response:localhost:22 $remote
fi
